version: '3.8'

services:

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:mysql://bd-fiap-ci-cd.mysql.database.azure.com:3306/gestao-residuos?createDatabaseIfNotExist=true
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PWD=${DATABASE_PWD}
    depends_on:
      - db
