-- Tabela de caminhões
CREATE TABLE TBL_CAMINHOES (
    CAMINHAO_ID INT AUTO_INCREMENT NOT NULL,
    LOCALIZACAO_ATUAL VARCHAR(255),
    STATUS VARCHAR(50),
    CONSTRAINT PK_CAMINHOES PRIMARY KEY (CAMINHAO_ID)
);

-- Tabela de recipientes
CREATE TABLE TBL_RECIPIENTES (
    RECIPIENTE_ID INT AUTO_INCREMENT NOT NULL,
    LOCALIZACAO VARCHAR(255) NOT NULL,
    CAPACIDADE INT NOT NULL,
    OCUPACAO INT NOT NULL,
    CONSTRAINT PK_RECIPIENTES PRIMARY KEY (RECIPIENTE_ID)
);

-- Tabela de coletas
CREATE TABLE TBL_COLETAS (
    COLETA_ID INT AUTO_INCREMENT NOT NULL,
    CAMINHAO_ID INT NOT NULL,
    RECIPIENTE_ID INT NOT NULL,
    DATA DATE NOT NULL,
    CONSTRAINT PK_COLETAS PRIMARY KEY (COLETA_ID),
    CONSTRAINT FK_COLETAS_CAMINHAO FOREIGN KEY (CAMINHAO_ID) REFERENCES TBL_CAMINHOES(CAMINHAO_ID),
    CONSTRAINT FK_COLETAS_RECIPIENTE FOREIGN KEY (RECIPIENTE_ID) REFERENCES TBL_RECIPIENTES(RECIPIENTE_ID)
);

-- Tabela de usuários
CREATE TABLE TBL_USUARIOS (
    USUARIO_ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'USER',
    CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO_ID)
);

-- Tabela de notificações
CREATE TABLE TBL_NOTIFICACOES (
    NOTIFICACAO_ID INT AUTO_INCREMENT NOT NULL,
    MENSAGEM VARCHAR(255) NOT NULL,
    DATA DATE NOT NULL,
    USUARIO VARCHAR(100),
    CONSTRAINT PK_NOTIFICACOES PRIMARY KEY (NOTIFICACAO_ID)
);
