version: '3.8'

services:
  db:
    container_name: mysql
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=api
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_pass

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:mysql://bd-fiap-ci-cd.mysql.database.azure.com:3306/api?createDatabaseIfNotExist=true
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PWD=${DATABASE_PWD}
    depends_on:
      - db
