name: CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Check if MySQL container exists
        run: |
          if [ $(docker ps -q -f name=my-mysql-container) ]; then
            echo "MySQL container is already running."
          else
            docker run --name my-mysql-container -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=db_gestaoresiduos -d mysql:latest
          fi

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Run Docker Container
        run: docker run --name myapp-container -d -p 8080:8080 myapp:latest

      - name: Verify App is Running
        run: curl http://localhost:8080
