name: CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: db_gestaoresiduos
          MYSQL_USER: root
          MYSQL_PASSWORD: 1234
        ports:
          - 3306:3306
        options: --health-cmd='mysqladmin ping --silent' --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Run Docker Container
        run: docker run --name myapp-container -d -p 8080:8080 myapp:latest

      - name: Verify App is Running
        run: curl http://localhost:8080
